# Contributors {#contrib}

This is a customized fork of the 
[awesome bookdown work](https://github.com/jennybc/happy-git-with-r)
from the authors below and full credit is due to them for their
efforts.  Local customization was done by Chuck Powell.

Jenny Bryan ([jennybryan.org](https://jennybryan.org)), Software Engineer at [RStudio](https://www.rstudio.com) on the [tidyverse](https://www.tidyverse.org)/[r-lib](https://github.com/r-lib/) team. Main author and content wrangler.

The development and delivery of this material has also benefited greatly from contributions by:

  * Dean Attali ([deanattali.com](http://deanattali.com)), Shiny consultant and [STAT 545](http://stat545.com) TA alum.
  * Bernhard Konrad, Software Engineer at Google and [STAT 545](http://stat545.com) TA alum.
  * Shaun Jackman ([sjackman.ca](http://sjackman.ca)), Bioinformatics Ph.D. student at UBC, lead maintainer of [Linuxbrew](http://linuxbrew.sh), and [STAT 545](http://stat545.com) TA alum.
  * Jim Hester ([jimhester.com](https://www.jimhester.com)), Software Engineer at [RStudio](https://www.rstudio.com) on the [tidyverse](https://www.tidyverse.org)/[r-lib](https://github.com/r-lib/) team.
  * A growing number of [GitHub contributors](https://github.com/jennybc/happy-git-with-r/graphs/contributors)
