# Register a GitHub account {#github-acct}

Register an account with GitHub. It's free!

  * <https://github.com>

**Registration Advice**

You can change a lot of settings in the future, so don't fret about any of that
now. **Except your username. You might want to give that some thought.**

A few tips, which sadly may contradict each other:

  * Use an email address you actually monitor and follow. The 
    most likely address is your ct.gov address unless you're
    already a GitHub user in which case you can stick with that.
  * Incorporate at least part of your actual name! People like to know who
    they're dealing with. Also makes your username easier for people to guess or
    remember.
  * Feel free to reuse your username from other contexts, e.g., Twitter or Slack.
  * Shorter is better than longer.

You can change your username later, but better to get this right the first time.

  * <https://help.github.com/articles/changing-your-github-username/>
  * <https://help.github.com/articles/what-happens-when-i-change-my-username/>

Go ahead and register your account **NOW**.  If you haven't already gotten
an email invitation from us let Deepti or Chuck know.

