# Install Git {#install-git}

You need Git, so RStudio can use it and so you can use it at the command line
(maybe).

If there's any chance it's installed already, verify that, rejoice, and skip this step.

Otherwise, find installation instructions below for your operating system.

```{r setup, include = FALSE}
has_bash <- Sys.which('bash') != '' && .Platform$OS.type != 'windows'
```

## Git already installed?

Go to the shell (Appendix \@ref(shell)). Enter `which git` to request the path
to your Git executable:

```{bash collapse = TRUE, eval = has_bash}
which git
```

and `git --version` to see its version:
 
```{bash collapse = TRUE, eval = has_bash}
git --version
```

If you are successful, that's great! You have Git already. No need to install!
Move on.

If, instead, you see something more like `git: command not found`, keep
reading.

macOS users might get an immediate offer to install command line developer
tools. Yes, you should accept! Click "Install" and read more below.

## Windows  {#install-git-windows}

Install [Git for Windows](https://git-for-windows.github.io/), also known as
`msysgit` or "Git Bash", to get Git in addition to some other useful tools, such
as the Bash shell. Yes, all those names are totally confusing, but you might
encounter them elsewhere and I want you to be well-informed.

We like this because Git for Windows leaves the Git executable in a conventional
location, which will help you and other programs, e.g. RStudio, find it and use
it. This also supports a transition to more expert use, because the "Git Bash"
shell will be useful as you venture outside of R/RStudio.

  * **NOTE:** When asked about "Adjusting your PATH environment", make sure to
    select "Git from the command line and also from 3rd-party software".
    Otherwise, we believe it is good to accept the defaults.
  * Note that RStudio for Windows prefers for Git to be installed below
    `C:/Program Files` and this appears to be the default. This implies, for
    example, that the Git executable on my Windows system is found at
    `C:/Program Files/Git/bin/git.exe`. Unless you have specific reasons to
    otherwise, follow this convention.

This also leaves you with a Git client, though not a very good one. So check out
Git clients we recommend (chapter \@ref(git-client)).

FYI, this appears to be equivalent to what you would download from here: <https://git-scm.com/download/>.

## macOS

**Option 1** (*highly recommended*): Install the Xcode command line tools (**not all of Xcode**), which includes Git.

Go to the shell and enter one of these commands to elicit an offer to install
developer command line tools:

``` bash
git --version
git config
```

Accept the offer! Click on "Install".

Here's another way to request this installation, more directly:

``` bash
xcode-select --install
```

We just happen to find this Git-based trigger apropos.

Note also that, after upgrading macOS, you might need to re-do the above and/or
re-agree to the Xcode license agreement. We have seen this cause the RStudio Git
pane to disappear on a system where it was previously working. Use commands like
those above to tickle Xcode into prompting you for what it needs, then restart
RStudio.

**Option 2** : If you anticipate getting heavily into scientific computing,
you're going to be installing and updating lots of software. You should check
out [Homebrew](http://brew.sh), "the missing package manager for OS X". Among
many other things, it can install Git for you. Once you have Homebrew installed,
do this in the shell:

```
brew install git
```
