# (PART) Installation {-} 

# Half the battle {#install-intro .unnumbered}

Getting all the necessary software installed, configured, and playing nicely
together is honestly half the battle when first adopting Git. Brace yourself for
some pain. The upside is that you can give yourself a pat on the back once you
get through this. And you __WILL__ get through this.

You will find far more resources for how to *use Git* than for installation and
configuration. Why? The experts ...

  * Have been doing this for years. It's simply not hard for them anymore.
  * Get more satisfaction and reward for thinking and writing about Git concepts and workflows than Git installation.

In their defense, it's hard to write installation instructions. Failures can be
specific to an individual OS or even individual computer. If you have some new
problem and, especially, the corresponding solution, 
[we'd love to hear from you!](https://github.com/ibecav/happy-git-with-r)

Our installation instructions are brand new, bear with us it's the hardest
part.
