# Register a GitHub account {#github-acct}

Register an account with GitHub. It's free!

  * <https://github.com>

## Username advice

You change a lot of settings in the future, so don't fret about any of that now.
**Except your username. You might want to give that some thought.**

A few tips, which sadly tend to contradict each other:

  * Incorporate your at least part of your actual name! People like to know who
    they're dealing with. Also makes your username easier for people to guess or
    remember.
  * Feel free to reuse your username from other contexts, e.g., Twitter or Slack.
  * Pick a username you will be comfortable revealing to your future boss.
  * Shorter is better than longer.
  * Be as unique as possible in as few characters as possible. In some settings
    GitHub auto-completes or suggests usernames.
  * Avoid words laden with special meaning in programming. In my first inept
    efforts to script around the GitHub API, I assigned lots of issues to 
    [the guy with username `NA`](https://github.com/na) because my vector of GitHub
    usernames contained missing values.
  * Avoid the use of upper vs. lower case to separate words. We highly recommend
    all lowercase. GitHub treats usernames in a case insensitive way, but using
    all lowercase is kinder to people doing downstream regular expression work
    with usernames, in various languages. A better strategy for word separation
    is to use an underscore `_`.

You can change your username later, but better to get this right the first time.

  * <https://help.github.com/articles/changing-your-github-username/>
  * <https://help.github.com/articles/what-happens-when-i-change-my-username/>

Go ahead and register your account **NOW** 

