# Quickstart -- tl;dr {#quickstart}

If you just want to get up and running and skip a lot of reading and not worry
about potential future issues, wants and needs then this is the place for you!

## The checklist simplified  {#checklist .unnumbered}

1. Register an account with GitHub (chapter \@ref(github-acct))
2. Install or upgrade R and RStudio (chapter \@ref(install-r-rstudio))
3. Install Git (chapter \@ref(install-git-windows))
4. Configure Git (chapter \@ref(hello-git))
5. **optional** Install a Git client (chapter \@ref(git-client))
6. Make sure it's all connected (chapter \@ref(rstudio-git-github))
7. Find that email where you were invited to the playground
   (https://github.com/ibecav/ctdph_playground)
8. Get **your** copy of the __playgound__ by **forking**
9. Make a copy of the fork (a clone) into your own RStudio (File > New Project >
   Version Control) (chapter \@ref(fork-and-clone))
10. Make sure you're set-up to track upstream changes (chapter
   \@ref(upstream-changes))
11. Start a new branch in your own copy of the repository -- remember don't
   touch master until you're sure! Work or play in other branches (chapter
   \@ref(dont-touch-master))
12. Play around, write code, or make modifications in your working branch. You're
   safe you're in a playground and you can't break anything and if all else
   fails you can burn it all down and start again! (chapter
   \@ref(burn))
13. Push some changes from **your** working branch of **your** working copy of
   the repo up to Github (the "push" button in RStudio).

   



   
   
   



